language: php

php:
    - 5.5
    - 5.6

before_script:
    - wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar
    - COMPOSER_ROOT_VERSION=dev-master composer install

script:
    - php php-cs-fixer.phar fix --dry-run -v
    - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
